# Generated by Django 5.0.2 on 2024-05-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0010_alter_usersettings_options_alter_usersettings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email address'),
        ),
    ]
