# Generated by Django 5.0.2 on 2024-05-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0012_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
