name: Backend Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:
    environment: Backend

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /home/runner/.docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-


    - name: Build the Docker image
      run: docker build -t backend .
      working-directory: ./apps/backend

    - name: Migrate the database
      run: docker run --rm backend python manage.py migrate
      working-directory: ./apps/backend

    - name: Test Django backend
      run: docker run --rm backend python manage.py test
      working-directory: ./apps/backend

