name: Backend Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag backend
      working-directory: ./apps/backend

    - name: Test the Docker image
      run: docker run --rm backend python manage.py test
      working-directory: ./apps/backend